name: My Github Actions Pipeline
on: 
  push:
    branches:
      - main
      - development
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8,3.9]
    steps:
      - uses: actions/checkout@v3
      - name: setup python in agent
        uses: actions/setup-python@v2
        with:
          python-version: ${{matrix.python-version}}
      - name: install dependencies
        run: | 
          python -m pipinstall --upgrade pip
          pip install pytest
      
        
          
